name: build-android

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['VERSION', 'android/**', '.github/**']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VEGA_KEYSTORE_BASE64: ${{ secrets.VEGA_KEYSTORE_BASE64 }}
      VEGA_KEYSTORE_PASSWORD: ${{ secrets.VEGA_KEYSTORE_PASSWORD }}
      VEGA_KEYSTORE_KEY_ALIAS: ${{ secrets.VEGA_KEYSTORE_KEY_ALIAS }}
      VEGA_KEYSTORE_KEY_PASSWORD: ${{ secrets.VEGA_KEYSTORE_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: ./.github/actions/build-android
        with:
          staging: releases-staging

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vega-android
          path: releases-staging/
          if-no-files-found: error